export const API_ENDPOINT = {
  REGISTER_PAGE: "api/auth/register",
  CREATE_CLASS: "/api/classes",
  GET_CLASS: "api/classes",
  EDIT_CLASS: "api/classes/",
  DELETE_CLASS:"api/classes/",
  ALL_USER:"api/users",
  CREATE_CHAPTERS:"api/classes/chapters",
  EDIT_CHAPTERS:"api/classes/chapters/",
  FORGOT_PASSWORD: "api/auth/forgot-password",
  RESET_PASSWORD: "api/auth/reset-password",
  AUTHENTICATED: "api/auth/authenticated",
  CLASSES: "api/classes",
  PAYMENTS: "api/payments",
  UPDATE_PAYMENTS: "api/payments/paid",
  FREE_CLASS: "api/users/class/access/free",
  WATCHED_VIDEOS: "api/users/videos/watched",
  LOGIN_USER : "api/auth/login",
  KATEGORI : "/api/general/categories",
  ALL_CLASS : "/api/classes",
  SEARCH : (query) => { return `/api/classes?search=${query}`},
  GET_ME : "/api/auth/authenticated",
  FREE_CLASS : (id) => { return `/api/users/class/access/free/${id}`},
  CLASS_CATEGORY : (id) => {return `/api/classes?category=${id}`}
};
